export const ACCESS_TO_BOARD_SUCCESS = "ACCESS_TO_BOARD_SUCCESS"
export const ACCESS_TO_BOARD_FAILED = "ACCESS_TO_BOARD_FAILED"


export const SHOW_LOADING = "SHOW_LOADING"
export const HIDE_LOADING = "HIDE_LOADING"

export const SAVE_BOARD_SUCCESS = "SAVE_BOARD_SUCCESS"
export const SAVE_BOARD_FAILED = "SAVE_BOARD_FAILED"


export const LOG_OUT = "LOG_OUT"